root = "."
tmp_dir = "/tmp/air"

[build]
  cmd = "go build -o /tmp/air/server ."
  bin = "/tmp/air/server"
  include_ext = ["go"]
  exclude_dir = ["migrations"]
  delay = 500

[log]
  time = false

[misc]
  clean_on_exit = true
